"""empty message

Revision ID: 017ac7c51695
Revises: c654241bcc33
Create Date: 2023-08-21 04:30:49.131915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017ac7c51695'
down_revision = 'c654241bcc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes_enviados', schema=None) as batch_op:
        batch_op.drop_column('isMessage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes_enviados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isMessage', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
