"""empty message

Revision ID: 02338924f382
Revises: 62c97a0c5624
Create Date: 2023-08-15 03:27:42.320317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02338924f382'
down_revision = '62c97a0c5624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=2000), nullable=True),
    sa.Column('url_imagen', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_content')
    # ### end Alembic commands ###
