"""empty message

Revision ID: 15904a2210f6
Revises: cec77046e592
Create Date: 2023-07-31 00:21:01.976268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15904a2210f6'
down_revision = 'cec77046e592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('url_imagen',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('perfil',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('perfil',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)
        batch_op.alter_column('url_imagen',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)

    # ### end Alembic commands ###
