"""empty message

Revision ID: 165d34e278ab
Revises: b7d1dfbf92e9
Create Date: 2023-08-16 22:37:07.344785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165d34e278ab'
down_revision = 'b7d1dfbf92e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condicion_funda', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('condicion_soporte', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vendedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['vendedor_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('pedido_articulos', schema=None) as batch_op:
        batch_op.alter_column('pedido_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('articulo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_articulos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('articulo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pedido_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vendedor_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('condicion_soporte')
        batch_op.drop_column('condicion_funda')

    # ### end Alembic commands ###
