"""empty message

Revision ID: 180c4c72af39
Revises: 8d0faf4e3d10
Create Date: 2023-08-19 20:40:29.032598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180c4c72af39'
down_revision = '8d0faf4e3d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valorado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('valorado')

    # ### end Alembic commands ###
