"""empty message

Revision ID: 1f8647c5c1a7
Revises: c5333d36f565
Create Date: 2023-08-21 03:49:21.615040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8647c5c1a7'
down_revision = 'c5333d36f565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bandeja_de_entrada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isMessage', sa.Boolean(), nullable=True))

    with op.batch_alter_table('mensajes_eliminados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isMessage', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes_eliminados', schema=None) as batch_op:
        batch_op.drop_column('isMessage')

    with op.batch_alter_table('bandeja_de_entrada', schema=None) as batch_op:
        batch_op.drop_column('isMessage')

    # ### end Alembic commands ###
