"""empty message

Revision ID: 257118754b20
Revises: 02338924f382
Create Date: 2023-08-15 22:53:15.942151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257118754b20'
down_revision = '02338924f382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.drop_column('posicion')

    # ### end Alembic commands ###
