"""empty message

Revision ID: 309eefca1031
Revises: 017ac7c51695
Create Date: 2023-08-21 04:31:06.935814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309eefca1031'
down_revision = '017ac7c51695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes_enviados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isMessage', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes_enviados', schema=None) as batch_op:
        batch_op.drop_column('isMessage')

    # ### end Alembic commands ###
