"""empty message

Revision ID: 3375b408ce5d
Revises: bd86117b584c
Create Date: 2023-07-30 21:14:02.611393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3375b408ce5d'
down_revision = 'bd86117b584c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('url_imagen',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('perfil',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('perfil',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('url_imagen',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
