"""empty message

Revision ID: 3a763c3af363
Revises: ddb308572f2c
Create Date: 2023-08-04 06:24:07.077472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a763c3af363'
down_revision = 'ddb308572f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('correo', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('contrasenha', sa.String(length=250), nullable=False))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_constraint('user_nombre_real_key', type_='unique')
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.create_unique_constraint(None, ['correo'])
        batch_op.create_unique_constraint(None, ['usuario'])
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.drop_column('nombre_real')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre_real', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_username_key', ['username'])
        batch_op.create_unique_constraint('user_nombre_real_key', ['nombre_real'])
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('contrasenha')
        batch_op.drop_column('correo')
        batch_op.drop_column('nombre')
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###
