"""empty message

Revision ID: 3de3f2865c2e
Revises: 3375b408ce5d
Create Date: 2023-07-30 23:54:48.299749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de3f2865c2e'
down_revision = '3375b408ce5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('url_imagen',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=800),
               existing_nullable=True)
        batch_op.alter_column('perfil',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=800),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('perfil',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('url_imagen',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
