"""empty message

Revision ID: 43bf47af1374
Revises: c5333d36f565
Create Date: 2023-08-20 02:01:30.454833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bf47af1374'
down_revision = 'c5333d36f565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aprobaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('articulo_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('subtitulo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('url_imagen',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=350),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_content', schema=None) as batch_op:
        batch_op.alter_column('url_imagen',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('subtitulo',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('aprobaciones', schema=None) as batch_op:
        batch_op.drop_column('articulo_id')

    # ### end Alembic commands ###
