"""empty message

Revision ID: 48a78d98ef6c
Revises: c4a913aa23ba
Create Date: 2023-07-26 01:51:04.595193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a78d98ef6c'
down_revision = 'c4a913aa23ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=250), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('nombre_real', sa.String(length=250), nullable=True),
    sa.Column('perfil', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precio_envio', sa.Integer(), nullable=True),
    sa.Column('precio_total', sa.Integer(), nullable=True),
    sa.Column('impuesto', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=250), nullable=True),
    sa.Column('artista_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('sello', sa.String(length=250), nullable=True),
    sa.Column('formato', sa.String(length=250), nullable=True),
    sa.Column('pais', sa.String(length=250), nullable=False),
    sa.Column('publicado', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=250), nullable=False),
    sa.Column('estilos', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['artista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sello')
    )
    op.create_table('bandeja_de_entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=250), nullable=True),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bandeja_de_entrada_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=250), nullable=True),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_eliminados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=250), nullable=True),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_enviados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=250), nullable=True),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('condicion_funda', sa.String(length=250), nullable=True),
    sa.Column('condicion_soporte', sa.String(length=250), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_articulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('posicion', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('nombre_real', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('mail', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('direccion_comprador', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('ciudad_comprador', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('estado_comprador', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('codigo_postal_comprador', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('pais_comprador', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('telefono_comprador', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('valoracion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cantidad_de_valoraciones', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['mail'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['nombre_real'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('is_admin')
        batch_op.drop_column('cantidad_de_valoraciones')
        batch_op.drop_column('valoracion')
        batch_op.drop_column('telefono_comprador')
        batch_op.drop_column('pais_comprador')
        batch_op.drop_column('codigo_postal_comprador')
        batch_op.drop_column('estado_comprador')
        batch_op.drop_column('ciudad_comprador')
        batch_op.drop_column('direccion_comprador')
        batch_op.drop_column('mail')
        batch_op.drop_column('nombre_real')
        batch_op.drop_column('username')

    op.drop_table('tracks')
    op.drop_table('pedido_articulos')
    op.drop_table('ofertas')
    op.drop_table('favoritos')
    op.drop_table('coleccion')
    op.drop_table('carrito')
    op.drop_table('mensajes_enviados')
    op.drop_table('mensajes_eliminados')
    op.drop_table('bandeja_de_entrada_admin')
    op.drop_table('bandeja_de_entrada')
    op.drop_table('articulo')
    op.drop_table('pedido')
    op.drop_table('artista')
    # ### end Alembic commands ###
