"""empty message

Revision ID: 48f54fdb1773
Revises: f5b595e086b9
Create Date: 2023-08-21 07:03:34.179229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f54fdb1773'
down_revision = 'f5b595e086b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('precio_envio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_envio', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
