"""empty message

Revision ID: 5efd1f4ef262
Revises: 3de3f2865c2e
Create Date: 2023-07-31 00:05:26.432633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efd1f4ef262'
down_revision = '3de3f2865c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('url_imagen',
               existing_type=sa.VARCHAR(length=800),
               type_=sa.String(length=1500),
               existing_nullable=True)
        batch_op.alter_column('perfil',
               existing_type=sa.VARCHAR(length=800),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('perfil',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=800),
               existing_nullable=True)
        batch_op.alter_column('url_imagen',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=800),
               existing_nullable=True)

    # ### end Alembic commands ###
