"""empty message

Revision ID: 65380ca82c64
Revises: 3505131f42fa
Create Date: 2023-08-21 07:21:52.200978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65380ca82c64'
down_revision = '3505131f42fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('haveShipping', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('haveShipping')

    # ### end Alembic commands ###
