"""empty message

Revision ID: 823b29f37c3b
Revises: 7a5cb11c500e
Create Date: 2023-08-11 18:29:15.043942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823b29f37c3b'
down_revision = '7a5cb11c500e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_ID_paypal', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('secret_key_paypal', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('secret_key_paypal')
        batch_op.drop_column('cliente_ID_paypal')

    # ### end Alembic commands ###
