"""empty message

Revision ID: 8d0faf4e3d10
Revises: ea0264335f54
Create Date: 2023-08-19 19:32:14.586411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0faf4e3d10'
down_revision = 'ea0264335f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valoraciones_posiitivas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valoraciones_negativas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('valoraciones_negativas')
        batch_op.drop_column('valoraciones_posiitivas')

    # ### end Alembic commands ###
