"""empty message

Revision ID: 93d238210e1a
Revises: 309eefca1031
Create Date: 2023-08-21 05:54:14.122021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d238210e1a'
down_revision = '309eefca1031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('valorado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valorado', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
