"""empty message

Revision ID: 9c4b350ce87a
Revises: 3a763c3af363
Create Date: 2023-08-08 20:56:01.827901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4b350ce87a'
down_revision = '3a763c3af363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aprobaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=250), nullable=True),
    sa.Column('artista_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('sello', sa.String(length=250), nullable=True),
    sa.Column('formato', sa.String(length=250), nullable=True),
    sa.Column('pais', sa.String(length=250), nullable=False),
    sa.Column('publicado', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=250), nullable=False),
    sa.Column('estilos', sa.String(length=250), nullable=True),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aprobaciones')
    # ### end Alembic commands ###
