"""empty message

Revision ID: c5333d36f565
Revises: 180c4c72af39
Create Date: 2023-08-19 23:01:45.097414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5333d36f565'
down_revision = '180c4c72af39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valoraciones_positivas', sa.Integer(), nullable=True))
        batch_op.drop_column('valoraciones_posiitivas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valoraciones_posiitivas', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('valoraciones_positivas')

    # ### end Alembic commands ###
