"""empty message

Revision ID: ddb308572f2c
Revises: 0bfca7930941
Create Date: 2023-08-04 05:56:19.387092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb308572f2c'
down_revision = '0bfca7930941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivo_mensajes_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=250), nullable=True),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=250), nullable=False))
        batch_op.alter_column('nombre_real',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_constraint('user_mail_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('mail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_mail_key', ['mail'])
        batch_op.alter_column('nombre_real',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('email')

    op.drop_table('archivo_mensajes_admin')
    # ### end Alembic commands ###
