"""empty message

Revision ID: fd686e3294f8
Revises: 62c97a0c5624
Create Date: 2023-08-14 23:28:32.434413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd686e3294f8'
down_revision = '62c97a0c5624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condicion_funda', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('condicion_soporte', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('articulo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vendedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['vendedor_id'], ['id'])
        batch_op.create_foreign_key(None, 'articulo', ['articulo_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vendedor_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('articulo_id')
        batch_op.drop_column('condicion_soporte')
        batch_op.drop_column('condicion_funda')

    # ### end Alembic commands ###
